server:
  port: 8081

spring:
  ai:
    openai:
      # This tells Spring: "Look for an environment variable named OPENAI_API_KEY"
      api-key: "${OPENAI_API_KEY}"
      chat:
        options:
          model: gpt-3.5-turbo

# Resilience Configuration
resilience4j:
  circuitbreaker:
    instances:
      aiService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000