server:
  port: 8081

spring:
  ai:
    openai:
      api-key: "${OPENAI_API_KEY}"
      chat:
        options:
          model: gpt-3.5-turbo

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000